In [133]:
import pandas as pd

In [134]:
base_original = pd.read_csv('../pasta_excel/processed.csv', sep='|')
base_original[['quartos', 'garagens']] = base_original[['quartos', 'garagens']].fillna(0).astype('int16')

base_original.describe()

,id_casa,precos,metragems,quartos,banheiros,garagens,preco_por_metro
count,1.483900e+04,1.483900e+04,14839.000000,14839.000000,14839.000000,14839.000000,14839.000000
mean,2.688824e+09,5.205726e+05,150.576184,2.626929,2.372262,2.171575,4281.260569
std,9.197583e+07,4.601219e+05,1335.515909,0.910568,1.466654,13.525954,2603.070110
min,7.586049e+07,2.300000e+04,10.000000,0.000000,1.000000,0.000000,2.810000
25%,2.657237e+09,2.600000e+05,64.000000,2.000000,1.000000,1.000000,2692.310000
50%,2.716522e+09,3.800000e+05,109.000000,3.000000,2.000000,2.000000,3741.180000
75%,2.739721e+09,6.000000e+05,172.000000,3.000000,3.000000,3.000000,5330.190000
max,2.750508e+09,6.800000e+06,160000.000000,20.000000,30.000000,1640.000000,159000.000000

In [135]:
base_original['tipo_imovel'].unique()

array(['apartamento', 'casa'], dtype=object)

In [136]:
base_apartamento = base_original[base_original['tipo_imovel'] == 'apartamento']
base_casa = base_original[base_original['tipo_imovel'] == 'casa']

In [137]:
base_apartamento.describe()

,id_casa,precos,metragems,quartos,banheiros,garagens,preco_por_metro
count,8.045000e+03,8.045000e+03,8045.00000,8045.000000,8045.000000,8045.000000,8045.000000
mean,2.693417e+09,4.826277e+05,89.68005,2.325420,2.114978,1.654195,5231.204235
std,9.011865e+07,4.511388e+05,95.01062,0.783505,1.349653,18.286051,2692.745252
min,7.586049e+07,6.595000e+04,10.00000,1.000000,1.000000,0.000000,39.660000
25%,2.667762e+09,2.200000e+05,48.00000,2.000000,1.000000,1.000000,3642.380000
50%,2.725072e+09,3.250000e+05,69.00000,2.000000,2.000000,1.000000,4750.000000
75%,2.741208e+09,5.781180e+05,107.00000,3.000000,3.000000,2.000000,6590.280000
max,2.750245e+09,6.800000e+06,4258.00000,20.000000,20.000000,1640.000000,159000.000000

In [138]:
base_casa.describe()

,id_casa,precos,metragems,quartos,banheiros,garagens,preco_por_metro
count,6.794000e+03,6.794000e+03,6794.000000,6794.000000,6794.000000,6794.000000,6794.000000
mean,2.683386e+09,5.655045e+05,222.685311,2.983956,2.676921,2.784221,3156.400871
std,9.384399e+07,4.665966e+05,1968.668303,0.921412,1.539597,1.723559,1969.874114
min,7.586051e+07,2.300000e+04,10.000000,0.000000,1.000000,0.000000,2.810000
25%,2.647376e+09,3.100000e+05,120.000000,2.000000,2.000000,2.000000,2150.135000
50%,2.713500e+09,4.260000e+05,165.000000,3.000000,2.000000,2.000000,2758.620000
75%,2.738857e+09,6.400000e+05,227.000000,3.000000,3.000000,4.000000,3673.470000
max,2.750508e+09,6.000000e+06,160000.000000,15.000000,30.000000,24.000000,56000.000000

# Total de imoveis por bairro

- Apartamento

In [139]:
base_apartamento.columns

Index(['id_casa', 'url', 'precos', 'enderecos_apartamentos', 'metragems',
       'quartos', 'banheiros', 'garagens', 'tipo_imovel', 'bairro',
       'preco_por_metro'],
      dtype='object')

In [140]:
base_apartamento['bairro'].value_counts().reset_index().head(50)

                              bairro  count
0                    Jardim Botânico    683
1                             Centro    673
2                       Nova Aliança    588
3                Jardim Olhos D Agua    298
4                       Jardim Irajá    255
5                         Ribeirânia    247
6                    Jardim Paulista    206
7                           Ipiranga    160
8             Jardim Palma Travassos    158
9                     Campos Eliseos    153
10                       Vila Seixas    151
11        Santa Cruz Do José Jacques    145
12                 Jardim Paulistano    130
13          Jardim Presidente Medici    127
14                   Bonfim Paulista    121
15  Residencial E Comercial Palmares    121
16                       Vila Amélia    117
17                    Vila Ana Maria    116
18                     Vila Virginia    116
19                Bosque Das Juritis    110
20                       Sumarezinho    109
21                     Jardim Sumare    108
22        Parque Industrial Lagoinha    107
23               Quinta Da Primavera     99
24                 Alto Da Boa Vista     97
25              Parque São Sebastião     97
26                      Vila Tibério     93
27     Reserva Sul Condomínio Resort     88
28                      Vila Do Golf     80
29           Parque Dos Bandeirantes     76
30                   Jardim São Luiz     70
31                          Iguatemi     69
32            Residencial Greenville     67
33                          Lagoinha     66
34                 Jardim Anhanguéra     65
35                     City Ribeirão     64
36               Jardim Santa Angela     62
37                  Parque Dos Lagos     62
38                       Jardim Zara     60
39                 Vila Monte Alegre     59
40               Jardim Manoel Penna     58
41                      Higienópolis     57
42           Jardim Nova Aliança Sul     55
43                  Planalto Verde I     53
44                      Reserva Real     53
45                   Nova Ribeirânia     51
46               Jardim Heitor Rigon     50
47            Condominio Mirante Sul     47
48          Residencial Das Americas     47
49               Residencial Flórida     47

- casa

In [141]:
base_casa['bairro'].value_counts().reset_index().head(50)

                                  bairro  count
0                         Campos Eliseos    477
1                               Ipiranga    339
2                             Ribeirânia    248
3                       Planalto Verde I    229
4                           Vila Tibério    220
5                        Bonfim Paulista    220
6                      Vila Monte Alegre    209
7                      Alto Da Boa Vista    184
8   Parque Residencial Cândido Portinari    169
9                          City Ribeirão    153
10                     Jardim Paulistano    138
11      Residencial E Comercial Palmares    134
12                         Vila Virginia    129
13                           Sumarezinho    122
14                       Jardim Paulista    111
15               Parque Dos Bandeirantes    100
16                 Parque Ribeirão Preto     99
17                         Jardim Sumare     98
18                       Jardim São Luiz     95
19            Jardim Jose Sampaio Junior     85
20                    Jardim Piratininga     80
21                      Jardim Antartica     80
22                      Alto Do Ipiranga     79
23                  Parque São Sebastião     76
24                         Independência     73
25                          Jardim Irajá     70
26                    Jardim Ouro Branco     69
27                                Centro     61
28                Jardim Cristo Redentor     59
29                        Vila Albertina     58
30                         Jardim Macedo     58
31                         Jardim Canadá     55
32                 Jardim Castelo Branco     55
33            Parque Industrial Lagoinha     52
34                     Quintino Facci Ii     48
35                        Vila Tamandaré     48
36                  Jardim Maria Goretti     47
37                 Parque Dos Flamboyans     45
38                        Jardim Recreio     45
39           Parque Residencial Lagoinha     44
40                     Jardim Anhanguéra     43
41                      Parque Dos Lagos     42
42                 Parque Dos Servidores     42
43                  Jardim Santa Cecilia     41
44                   Jardim Heitor Rigon     41
45                              Lagoinha     41
46                        Jardim América     40
47                  Jardim Independencia     40
48                   Jardim Angelo Jurca     39
49                  Parque Das Oliveiras     38

- Bairros sorteados

In [142]:
bairros_apartamentos = ['Jardim Botânico', 'Centro', 'Nova Aliança', 'Jardim Olhos D Agua', 'Sumarezinho' , 'Condominio Mirante Sul']
bairros_casas = ['Campos Eliseos', 'Ipiranga', 'Ribeirânia', 'Planalto Verde I','Vila Tibério', 'Sumarezinho']

# Média, Moda , médiana e desvio padrão

In [154]:
def obter_resumo_estatistica(dataframe: pd.DataFrame):
    print(f'Média preço: {round(dataframe["precos"].mean(), 2)}')
    print(f'Moda preço: {round(dataframe["precos"].mode(), 2)}')
    print(f'Mediana preço: {round(dataframe["precos"].median(), 2)}')
    print(
        f'Desvio Padrão preço: {round(dataframe["precos"].std(), 2)}')
    print(f'Preço Máximo: {round(dataframe["precos"].max(), 2)}')
    print(f'Preço Minimo: {round(dataframe["precos"].min(), 2)}')
    print(f'Total imóveis: {dataframe.shape[0]}')

- Apartamento

In [155]:
for bairro in bairros_apartamentos:

    df_temp = base_apartamento.query(f'bairro == "{bairro}"')
    print('=' * 40)
    print(f'Bairro: {bairro}')
    obter_resumo_estatistica(dataframe=df_temp)
    for banheiro in sorted(df_temp['banheiros'].unique()):
        
        df_banheiro = df_temp.query(f'banheiros == {banheiro}')
        if not df_banheiro.empty:
            print(f'====Análise banheiro {banheiro}=========')
            obter_resumo_estatistica(dataframe=df_banheiro)

    print('=' * 40)

========================================
Bairro: Jardim Botânico
Média preço: 805287.04
Moda preço: 0    850000.0
Name: precos, dtype: float64
Mediana preço: 670000.0
Desvio Padrão preço: 516998.36
Preço Máximo: 6800000.0
Preço Minimo: 180000.0
Total imóveis: 683
====Análise banheiro 1=========
Média preço: 411632.93
Moda preço: 0    320000.0
1    350000.0
Name: precos, dtype: float64
Mediana preço: 350000.0
Desvio Padrão preço: 174232.65
Preço Máximo: 1100000.0
Preço Minimo: 180000.0
Total imóveis: 121
====Análise banheiro 2=========
Média preço: 560655.47
Moda preço: 0    550000.0
Name: precos, dtype: float64
Mediana preço: 541000.0
Desvio Padrão preço: 209332.76
Preço Máximo: 1780000.0
Preço Minimo: 225000.0
Total imóveis: 210
====Análise banheiro 3=========
Média preço: 772016.32
Moda preço: 0    900000.0
Name: precos, dtype: float64
Mediana preço: 750000.0
Desvio Padrão preço: 307732.72
Preço Máximo: 1826000.0
Preço Minimo: 325000.0
Total imóveis: 102
====Análise banheiro 4=========
Média preço: 951578.31
Moda preço: 0    850000.0
Name: precos, dtype: float64
Mediana preço: 870000.0
Desvio Padrão preço: 293920.06
Preço Máximo: 2100000.0
Preço Minimo: 480000.0
Total imóveis: 91
====Análise banheiro 5=========
Média preço: 1229215.14
Moda preço: 0    850000.0
Name: precos, dtype: float64
Mediana preço: 1200000.0
Desvio Padrão preço: 389123.23
Preço Máximo: 2505944.0
Preço Minimo: 560000.0
Total imóveis: 136
====Análise banheiro 6=========
Média preço: 2173954.19
Moda preço: 0    1490000.0
Name: precos, dtype: float64
Mediana preço: 1765000.0
Desvio Padrão preço: 1323274.48
Preço Máximo: 6800000.0
Preço Minimo: 1100000.0
Total imóveis: 16
====Análise banheiro 7=========
Média preço: 2386666.67
Moda preço: 0     990000.0
1    2350000.0
2    2490000.0
3    2590000.0
4    2900000.0
5    3000000.0
Name: precos, dtype: float64
Mediana preço: 2540000.0
Desvio Padrão preço: 727149.69
Preço Máximo: 3000000.0
Preço Minimo: 990000.0
Total imóveis: 6
====Análise banheiro 8=========
Média preço: 850000.0
Moda preço: 0    850000.0
Name: precos, dtype: float64
Mediana preço: 850000.0
Desvio Padrão preço: nan
Preço Máximo: 850000.0
Preço Minimo: 850000.0
Total imóveis: 1
========================================
========================================
Bairro: Centro
Média preço: 414824.66
Moda preço: 0    450000.0
Name: precos, dtype: float64
Mediana preço: 370000.0
Desvio Padrão preço: 214865.42
Preço Máximo: 1600000.0
Preço Minimo: 88672.0
Total imóveis: 673
====Análise banheiro 1=========
Média preço: 263061.05
Moda preço: 0    150000.0
1    220000.0
Name: precos, dtype: float64
Mediana preço: 230000.0
Desvio Padrão preço: 126886.01
Preço Máximo: 850000.0
Preço Minimo: 88672.0
Total imóveis: 183
====Análise banheiro 2=========
Média preço: 374854.55
Moda preço: 0    300000.0
Name: precos, dtype: float64
Mediana preço: 350000.0
Desvio Padrão preço: 131906.6
Preço Máximo: 980000.0
Preço Minimo: 108000.0
Total imóveis: 186
====Análise banheiro 3=========
Média preço: 431190.6
Moda preço: 0    350000.0
Name: precos, dtype: float64
Mediana preço: 405000.0
Desvio Padrão preço: 132397.93
Preço Máximo: 1300000.0
Preço Minimo: 235000.0
Total imóveis: 183
====Análise banheiro 4=========
Média preço: 619684.93
Moda preço: 0    600000.0
Name: precos, dtype: float64
Mediana preço: 600000.0
Desvio Padrão preço: 228902.55
Preço Máximo: 1500000.0
Preço Minimo: 259000.0
Total imóveis: 73
====Análise banheiro 5=========
Média preço: 758342.11
Moda preço: 0    650000.0
1    750000.0
2    850000.0
Name: precos, dtype: float64
Mediana preço: 750000.0
Desvio Padrão preço: 279536.32
Preço Máximo: 1600000.0
Preço Minimo: 290000.0
Total imóveis: 38
====Análise banheiro 6=========
Média preço: 945000.0
Moda preço: 0     630000.0
1     750000.0
2    1100000.0
3    1300000.0
Name: precos, dtype: float64
Mediana preço: 925000.0
Desvio Padrão preço: 309461.9
Preço Máximo: 1300000.0
Preço Minimo: 630000.0
Total imóveis: 4
====Análise banheiro 7=========
Média preço: 630666.67
Moda preço: 0    450000.0
1    530000.0
2    912000.0
Name: precos, dtype: float64
Mediana preço: 530000.0
Desvio Padrão preço: 246903.49
Preço Máximo: 912000.0
Preço Minimo: 450000.0
Total imóveis: 3
====Análise banheiro 8=========
Média preço: 590000.0
Moda preço: 0    590000.0
Name: precos, dtype: float64
Mediana preço: 590000.0
Desvio Padrão preço: 0.0
Preço Máximo: 590000.0
Preço Minimo: 590000.0
Total imóveis: 2
====Análise banheiro 11=========
Média preço: 1500000.0
Moda preço: 0    1500000.0
Name: precos, dtype: float64
Mediana preço: 1500000.0
Desvio Padrão preço: nan
Preço Máximo: 1500000.0
Preço Minimo: 1500000.0
Total imóveis: 1
========================================
========================================
Bairro: Nova Aliança
Média preço: 563808.4
Moda preço: 0    250000.0
Name: precos, dtype: float64
Mediana preço: 480000.0
Desvio Padrão preço: 337244.54
Preço Máximo: 3400000.0
Preço Minimo: 175000.0
Total imóveis: 588
====Análise banheiro 1=========
Média preço: 303011.42
Moda preço: 0    250000.0
Name: precos, dtype: float64
Mediana preço: 265000.0
Desvio Padrão preço: 155556.53
Preço Máximo: 1350000.0
Preço Minimo: 175000.0
Total imóveis: 196
====Análise banheiro 2=========
Média preço: 464948.51
Moda preço: 0    380000.0
Name: precos, dtype: float64
Mediana preço: 425000.0
Desvio Padrão preço: 162874.73
Preço Máximo: 1420000.0
Preço Minimo: 191185.0
Total imóveis: 159
====Análise banheiro 3=========
Média preço: 654488.93
Moda preço: 0    578118.0
Name: precos, dtype: float64
Mediana preço: 617900.0
Desvio Padrão preço: 156348.13
Preço Máximo: 1100000.0
Preço Minimo: 350000.0
Total imóveis: 113
====Análise banheiro 4=========
Média preço: 906485.14
Moda preço: 0     920000.0
1    1200000.0
Name: precos, dtype: float64
Mediana preço: 920000.0
Desvio Padrão preço: 221568.15
Preço Máximo: 1420000.0
Preço Minimo: 530000.0
Total imóveis: 57
====Análise banheiro 5=========
Média preço: 1115732.05
Moda preço: 0    1300000.0
Name: precos, dtype: float64
Mediana preço: 1128771.0
Desvio Padrão preço: 219048.19
Preço Máximo: 1500000.0
Preço Minimo: 674000.0
Total imóveis: 62
====Análise banheiro 7=========
Média preço: 3400000.0
Moda preço: 0    3400000.0
Name: precos, dtype: float64
Mediana preço: 3400000.0
Desvio Padrão preço: nan
Preço Máximo: 3400000.0
Preço Minimo: 3400000.0
Total imóveis: 1
========================================
========================================
Bairro: Jardim Olhos D Agua
Média preço: 1088655.48
Moda preço: 0    2500000.0
Name: precos, dtype: float64
Mediana preço: 990000.0
Desvio Padrão preço: 504324.38
Preço Máximo: 4450000.0
Preço Minimo: 343649.0
Total imóveis: 298
====Análise banheiro 1=========
Média preço: 642458.0
Moda preço: 0     343649.0
1     385000.0
2     500000.0
3     594869.0
4     772600.0
5    1258630.0
Name: precos, dtype: float64
Mediana preço: 547434.5
Desvio Padrão preço: 339038.44
Preço Máximo: 1258630.0
Preço Minimo: 343649.0
Total imóveis: 6
====Análise banheiro 2=========
Média preço: 622691.11
Moda preço: 0    600000.0
Name: precos, dtype: float64
Mediana preço: 598781.0
Desvio Padrão preço: 160334.08
Preço Máximo: 1254000.0
Preço Minimo: 350000.0
Total imóveis: 63
====Análise banheiro 3=========
Média preço: 981826.51
Moda preço: 0    1100000.0
1    1200000.0
Name: precos, dtype: float64
Mediana preço: 929000.0
Desvio Padrão preço: 227867.55
Preço Máximo: 1519000.0
Preço Minimo: 560000.0
Total imóveis: 37
====Análise banheiro 4=========
Média preço: 1173164.43
Moda preço: 0    2500000.0
Name: precos, dtype: float64
Mediana preço: 1020000.0
Desvio Padrão preço: 421500.61
Preço Máximo: 2500000.0
Preço Minimo: 754524.0
Total imóveis: 119
====Análise banheiro 5=========
Média preço: 1350555.52
Moda preço: 0    1211830.0
1    1250000.0
2    1350000.0
Name: precos, dtype: float64
Mediana preço: 1240566.5
Desvio Padrão preço: 449476.58
Preço Máximo: 3180000.0
Preço Minimo: 847500.0
Total imóveis: 64
====Análise banheiro 6=========
Média preço: 2107260.56
Moda preço: 0    1683522.0
Name: precos, dtype: float64
Mediana preço: 1683522.0
Desvio Padrão preço: 996038.28
Preço Máximo: 4450000.0
Preço Minimo: 1372000.0
Total imóveis: 9
========================================
========================================
Bairro: Sumarezinho
Média preço: 248541.06
Moda preço: 0    250000.0
Name: precos, dtype: float64
Mediana preço: 235000.0
Desvio Padrão preço: 63597.11
Preço Máximo: 450000.0
Preço Minimo: 140000.0
Total imóveis: 109
====Análise banheiro 1=========
Média preço: 227046.03
Moda preço: 0    250000.0
Name: precos, dtype: float64
Mediana preço: 220000.0
Desvio Padrão preço: 56235.08
Preço Máximo: 425000.0
Preço Minimo: 140000.0
Total imóveis: 69
====Análise banheiro 2=========
Média preço: 284126.32
Moda preço: 0    230000.0
1    268000.0
Name: precos, dtype: float64
Mediana preço: 268000.0
Desvio Padrão preço: 59885.43
Preço Máximo: 450000.0
Preço Minimo: 200000.0
Total imóveis: 38
====Análise banheiro 3=========
Média preço: 298000.0
Moda preço: 0    298000.0
Name: precos, dtype: float64
Mediana preço: 298000.0
Desvio Padrão preço: nan
Preço Máximo: 298000.0
Preço Minimo: 298000.0
Total imóveis: 1
====Análise banheiro 4=========
Média preço: 330000.0
Moda preço: 0    330000.0
Name: precos, dtype: float64
Mediana preço: 330000.0
Desvio Padrão preço: nan
Preço Máximo: 330000.0
Preço Minimo: 330000.0
Total imóveis: 1
========================================
========================================
Bairro: Condominio Mirante Sul
Média preço: 232217.02
Moda preço: 0    230000.0
Name: precos, dtype: float64
Mediana preço: 230000.0
Desvio Padrão preço: 26161.8
Preço Máximo: 300000.0
Preço Minimo: 180000.0
Total imóveis: 47
====Análise banheiro 1=========
Média preço: 230663.64
Moda preço: 0    230000.0
Name: precos, dtype: float64
Mediana preço: 230000.0
Desvio Padrão preço: 24481.06
Preço Máximo: 290000.0
Preço Minimo: 180000.0
Total imóveis: 44
====Análise banheiro 2=========
Média preço: 255000.0
Moda preço: 0    210000.0
1    255000.0
2    300000.0
Name: precos, dtype: float64
Mediana preço: 255000.0
Desvio Padrão preço: 45000.0
Preço Máximo: 300000.0
Preço Minimo: 210000.0
Total imóveis: 3
========================================

- Casas

In [110]:
for bairro in bairros_casas:

    df_temp = base_casa.query(f'bairro == "{bairro}"')
    print('=' * 40)
    print(f'Bairro: {bairro}')
    print(f'Média preço: {round(df_temp["precos"].mean(), 2)}')
    print(f'Moda preço: {round(df_temp["precos"].mode(), 2)}')
    print(f'Mediana preço: {round(df_temp["precos"].median(), 2)}')
    print(f'Desvio Padrão preço: {round(df_temp["precos"].std(), 2)}')
    print(f'Preço Máximo: {round(df_temp["precos"].max(), 2)}')
    print(f'Preço Minimo: {round(df_temp["precos"].min(), 2)}')

    for banheiro in df_temp['banheiros'].unique():
      
        df_temp = df_temp.query(f'banheiros == {banheiro}')
        if not  df_temp.empty:
            print(f'====Análise banheiro {banheiro}=========')
            print(f'Média preço: {round(df_temp["precos"].mean(), 2)}')
            print(f'Moda preço: {round(df_temp["precos"].mode(), 2)}')
            print(f'Mediana preço: {round(df_temp["precos"].median(), 2)}')
            print(f'Desvio Padrão preço: {round(df_temp["precos"].std(), 2)}')
            print(f'Preço Máximo: {round(df_temp["precos"].max(), 2)}')
            print(f'Preço Minimo: {round(df_temp["precos"].min(), 2)}')
    print('=' * 40)

========================================
Bairro: Campos Eliseos
Média preço: 385265.41
Moda preço: 0    320000.0
Name: precos, dtype: float64
Mediana preço: 340000.0
Desvio Padrão preço: 182572.6
Preço Máximo: 1700000.0
Preço Minimo: 110000.0
====Análise banheiro 1=========
Média preço: 310199.32
Moda preço: 0    250000.0
1    320000.0
Name: precos, dtype: float64
Mediana preço: 282500.0
Desvio Padrão preço: 171861.19
Preço Máximo: 1700000.0
Preço Minimo: 110000.0
========================================
========================================
Bairro: Ipiranga
Média preço: 353410.62
Moda preço: 0    270000.0
Name: precos, dtype: float64
Mediana preço: 300000.0
Desvio Padrão preço: 318745.84
Preço Máximo: 5500000.0
Preço Minimo: 120000.0
====Análise banheiro 1=========
Média preço: 286769.29
Moda preço: 0    250000.0
Name: precos, dtype: float64
Mediana preço: 270000.0
Desvio Padrão preço: 100290.2
Preço Máximo: 750000.0
Preço Minimo: 120000.0
========================================
========================================
Bairro: Ribeirânia
Média preço: 1144110.24
Moda preço: 0    800000.0
Name: precos, dtype: float64
Mediana preço: 975000.0
Desvio Padrão preço: 572278.18
Preço Máximo: 6000000.0
Preço Minimo: 530000.0
====Análise banheiro 5=========
Média preço: 1238248.0
Moda preço: 0    800000.0
Name: precos, dtype: float64
Mediana preço: 1015000.0
Desvio Padrão preço: 801778.25
Preço Máximo: 6000000.0
Preço Minimo: 720000.0
========================================
========================================
Bairro: Planalto Verde I
Média preço: 421754.98
Moda preço: 0    320000.0
Name: precos, dtype: float64
Mediana preço: 370000.0
Desvio Padrão preço: 209084.16
Preço Máximo: 1900000.0
Preço Minimo: 205000.0
====Análise banheiro 4=========
Média preço: 579400.0
Moda preço: 0    390000.0
1    480000.0
2    500000.0
3    550000.0
4    580000.0
5    583000.0
6    610000.0
7    630000.0
8    721000.0
9    750000.0
Name: precos, dtype: float64
Mediana preço: 581500.0
Desvio Padrão preço: 108313.54
Preço Máximo: 750000.0
Preço Minimo: 390000.0
========================================
========================================
Bairro: Vila Tibério
Média preço: 402263.18
Moda preço: 0    320000.0
1    330000.0
Name: precos, dtype: float64
Mediana preço: 367500.0
Desvio Padrão preço: 150464.47
Preço Máximo: 1100000.0
Preço Minimo: 150000.0
====Análise banheiro 1=========
Média preço: 320712.12
Moda preço: 0    250000.0
Name: precos, dtype: float64
Mediana preço: 289500.0
Desvio Padrão preço: 114058.12
Preço Máximo: 700000.0
Preço Minimo: 150000.0
========================================
========================================
Bairro: Sumarezinho
Média preço: 457753.98
Moda preço: 0    520000.0
Name: precos, dtype: float64
Mediana preço: 450000.0
Desvio Padrão preço: 142894.75
Preço Máximo: 1000000.0
Preço Minimo: 183000.0
====Análise banheiro 2=========
Média preço: 408595.24
Moda preço: 0    520000.0
Name: precos, dtype: float64
Mediana preço: 402500.0
Desvio Padrão preço: 109071.71
Preço Máximo: 800000.0
Preço Minimo: 183000.0
========================================

# Preço por metro